version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/app/static:ro
    depends_on:
      - lite-server
      - json-server

  lite-server:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app/static
      - ./bs-config.json:/app/bs-config.json
    command: sh -c "npm install -g lite-server && lite-server --config bs-config.json --no-open"
    deploy:
      replicas: 3

  json-server:
    image: node
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: sh -c "npm install -g json-server && json-server --watch data/db.json --host 0.0.0.0"
    deploy:
      replicas: 3

